-- =========================================================
-- QL_MYNGHE - HỆ THỐNG QUẢN LÝ CỬA HÀNG MỸ NGHỆ
-- =========================================================
DROP DATABASE IF EXISTS QL_MYNGHE;
CREATE DATABASE QL_MYNGHE
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
USE QL_MYNGHE;

-- =========================
-- DANHMUCSANPHAM
-- =========================
CREATE TABLE DANHMUCSANPHAM 
(
    MADANHMUC INT NOT NULL AUTO_INCREMENT,
    TENDANHMUC VARCHAR(100) NOT NULL,
    PRIMARY KEY (MADANHMUC)
) ENGINE=InnoDB;

-- =========================
-- LOAI
-- =========================
CREATE TABLE LOAI 
(
    MALOAI VARCHAR(10) NOT NULL,
    TENLOAI VARCHAR(50) NOT NULL,
    MADANHMUC INT,
    PRIMARY KEY (MALOAI),
    CONSTRAINT FK_LOAI_DANHMUC
        FOREIGN KEY (MADANHMUC) REFERENCES DANHMUCSANPHAM(MADANHMUC)
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================
-- KHUYENMAI
-- =========================
CREATE TABLE KHUYENMAI 
(
    MAKHUYENMAI VARCHAR(10) NOT NULL,
    LOAIKHUYENMAI VARCHAR(50),
    TENKHUYENMAI VARCHAR(100),
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,
    GIAMGIA DECIMAL(5,2),
    PRIMARY KEY (MAKHUYENMAI)
) ENGINE=InnoDB;

-- =========================
-- NHACUNGCAP
-- =========================
CREATE TABLE NHACUNGCAP 
(
    MANHACUNGCAP INT NOT NULL AUTO_INCREMENT,
    TENNHACUNGCAP VARCHAR(100) NOT NULL,
    DTHOAI VARCHAR(20),
    DIACHI VARCHAR(255),
    PRIMARY KEY (MANHACUNGCAP)
) ENGINE=InnoDB;

-- =========================
-- NGUOIDUNG / QUYEN
-- =========================
CREATE TABLE NGUOIDUNG 
(
    MANGUOIDUNG VARCHAR(10) NOT NULL,
    TENNGUOIDUNG VARCHAR(50) NOT NULL,
    TAIKHOAN VARCHAR(255) NOT NULL UNIQUE,
    MATKHAU VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255),
    SODIENTHOAI VARCHAR(20),
    PRIMARY KEY (MANGUOIDUNG)
) ENGINE=InnoDB;

CREATE TABLE QUYEN 
(
    MAQUYEN VARCHAR(10) NOT NULL,
    TENQUYEN VARCHAR(50) NOT NULL,
    PRIMARY KEY (MAQUYEN)
) ENGINE=InnoDB;

CREATE TABLE QUYEN_NGUOIDUNG 
(
    MANGUOIDUNG VARCHAR(10) NOT NULL,
    MAQUYEN VARCHAR(10) NOT NULL,
    PRIMARY KEY (MANGUOIDUNG, MAQUYEN),
    FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG) ON DELETE CASCADE,
    FOREIGN KEY (MAQUYEN) REFERENCES QUYEN(MAQUYEN)
) ENGINE=InnoDB;

-- =========================
-- KHÁCH HÀNG & ĐỊA CHỈ
-- =========================
CREATE TABLE KHACHHANG (
    MAKHACHHANG INT NOT NULL AUTO_INCREMENT,
    MANGUOIDUNG VARCHAR(10),
    HOTEN VARCHAR(50) NOT NULL,
    SODIENTHOAI VARCHAR(10),
    EMAIL VARCHAR(255),
    PRIMARY KEY (MAKHACHHANG),
    FOREIGN KEY (MANGUOIDUNG) REFERENCES NGUOIDUNG(MANGUOIDUNG) ON DELETE CASCADE
) ENGINE=InnoDB;

    CREATE TABLE DIACHI_GIAOHANG (
    MADIACHI INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG INT NOT NULL,
    DIACHI VARCHAR(255),
    PRIMARY KEY (MADIACHI),
    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- =========================
-- HÌNH THỨC THANH TOÁN
-- =========================
CREATE TABLE HINHTHUCTT (
    MATT VARCHAR(10) NOT NULL,
    LOAITT VARCHAR(255),
    PRIMARY KEY (MATT)
) ENGINE=InnoDB;

-- =========================
-- SẢN PHẨM
-- =========================
CREATE TABLE SANPHAM 
(
    MASANPHAM VARCHAR(10) NOT NULL,
    TENSANPHAM VARCHAR(255) NOT NULL,
    HINHANH VARCHAR(255),
    GIABAN DECIMAL(18,0),
    SOLUONGTON INT,
    MOTA VARCHAR(1000),
    MALOAI VARCHAR(10),
    MAKHUYENMAI VARCHAR(10),
    MANHACUNGCAP INT,
    PRIMARY KEY (MASANPHAM),
    FOREIGN KEY (MALOAI) REFERENCES LOAI(MALOAI) ON DELETE CASCADE,
    FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI) ON DELETE SET NULL,
    FOREIGN KEY (MANHACUNGCAP) REFERENCES NHACUNGCAP(MANHACUNGCAP) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Liên kết SP - KM (nếu 1 SP có nhiều KM)
CREATE TABLE SANPHAM_KHUYENMAI 
(
    MASANPHAM VARCHAR(10) NOT NULL,
    MAKHUYENMAI VARCHAR(10) NOT NULL,
    PRIMARY KEY (MASANPHAM, MAKHUYENMAI),
    FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM),
    FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI)
) ENGINE=InnoDB;

-- Đánh giá
CREATE TABLE DANHGIA 
(
    MADANHGIA INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG INT NOT NULL,
    MASANPHAM VARCHAR(10) NOT NULL,
    DIEMSO INT CHECK (DIEMSO BETWEEN 1 AND 5),
    NHANXET VARCHAR(1000),
    NGAYDANHGIA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MADANHGIA),
    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE CASCADE,
    FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
) ENGINE=InnoDB;

-- =========================
-- ĐƠN HÀNG
-- =========================
CREATE TABLE DONHANG 
(
    MADONHANG INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG INT NOT NULL,
    MADIACHI INT NOT NULL,
    NGAYGIAO DATETIME NULL,
    NGAYDAT DATETIME NULL,
    MATT VARCHAR(10),
    GHICHU VARCHAR(255),
    TONGSLHANG INT,
    TONGTHANHTIEN DECIMAL(18,0),
    TRANGTHAI VARCHAR(50) DEFAULT 'Chờ xử lý',
    PRIMARY KEY (MADONHANG),
    FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE CASCADE,
    FOREIGN KEY (MADIACHI) REFERENCES DIACHI_GIAOHANG(MADIACHI) ON DELETE RESTRICT,
    FOREIGN KEY (MATT) REFERENCES HINHTHUCTT(MATT)
) ENGINE=InnoDB;

CREATE TABLE CHITIETDONHANG 
(
    MADONHANG INT NOT NULL,
    MASANPHAM VARCHAR(10) NOT NULL,
    SOLUONG INT,
    DONGIA DECIMAL(18,0),
    PRIMARY KEY (MADONHANG, MASANPHAM),
    FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG) ON DELETE CASCADE,
    FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
) ENGINE=InnoDB;


