-- =========================================================
-- QL_MYNGHE - HỆ THỐNG QUẢN LÝ CỬA HÀNG MỸ NGHỆ (Laravel UI)
-- =========================================================
DROP DATABASE IF EXISTS QL_MYNGHE;
CREATE DATABASE QL_MYNGHE
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
USE QL_MYNGHE;

-- =========================================================
-- DANHMUCSANPHAM
-- =========================================================
CREATE TABLE DANHMUCSANPHAM 
(
    MADANHMUC INT NOT NULL AUTO_INCREMENT,
    TENDANHMUC VARCHAR(100) NOT NULL,
    PRIMARY KEY (MADANHMUC)
) ENGINE=InnoDB;

-- =========================================================
-- LOAI
-- =========================================================
CREATE TABLE LOAI 
(
    MALOAI VARCHAR(10) NOT NULL,
    TENLOAI VARCHAR(50) NOT NULL,
    MADANHMUC INT,
    PRIMARY KEY (MALOAI),
    KEY IX_LOAI_MADANHMUC (MADANHMUC),
    CONSTRAINT FK_LOAI_DANHMUC
        FOREIGN KEY (MADANHMUC) REFERENCES DANHMUCSANPHAM(MADANHMUC)
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- KHUYENMAI
-- =========================================================
CREATE TABLE KHUYENMAI 
(
    MAKHUYENMAI   VARCHAR(10)  NOT NULL,
    LOAIKHUYENMAI VARCHAR(50),             -- 'Giảm %' | 'Giảm fixed' | 'Flash Sale' | ...
    TENKHUYENMAI  VARCHAR(100),
    NGAYBATDAU    DATETIME,
    NGAYKETTHUC   DATETIME,
    GIAMGIA DECIMAL(12,2) NOT NULL DEFAULT 0,

    -- Phạm vi & cấu hình mềm để hỗ trợ 2 mô hình
    PHAMVI        ENUM('ORDER','PRODUCT') NOT NULL DEFAULT 'PRODUCT',
    DIEUKIEN_JSON JSON NULL,               -- { non_stackable, min_order_total, max_discount, targets{...} }
    UUTIEN        INT NOT NULL DEFAULT 10, -- Ưu tiên chồng khuyến mãi (cao hơn = ưu tiên hơn)

    PRIMARY KEY (MAKHUYENMAI),
    KEY IX_KM_DATE (NGAYBATDAU, NGAYKETTHUC),
    KEY IX_KM_PHAMVI (PHAMVI),
    KEY IX_KM_LOAI (LOAIKHUYENMAI)
) ENGINE=InnoDB;

-- =========================================================
-- NHACUNGCAP
-- =========================================================
CREATE TABLE NHACUNGCAP 
(
    MANHACUNGCAP INT NOT NULL AUTO_INCREMENT,
    TENNHACUNGCAP VARCHAR(100) NOT NULL,
    DTHOAI VARCHAR(20),
    DIACHI VARCHAR(255),
    PRIMARY KEY (MANHACUNGCAP),
    KEY IX_NCC_TEN (TENNHACUNGCAP)
) ENGINE=InnoDB;

-- =========================================================
-- USERS / QUYEN
-- =========================================================
CREATE TABLE users 
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    remember_token VARCHAR(100),
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB;

-- =========================================================
-- PASSWORD RESETS
-- =========================================================
CREATE TABLE password_resets (
    email VARCHAR(255) NOT NULL,
    token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NULL DEFAULT NULL,
    PRIMARY KEY (email)
) ENGINE=InnoDB;

CREATE TABLE QUYEN 
(
    MAQUYEN VARCHAR(10) NOT NULL,
    TENQUYEN VARCHAR(50) NOT NULL,
    PRIMARY KEY (MAQUYEN)
) ENGINE=InnoDB;

CREATE TABLE QUYEN_NGUOIDUNG 
(
    user_id BIGINT UNSIGNED NOT NULL,
    MAQUYEN VARCHAR(10) NOT NULL,
    PRIMARY KEY (user_id, MAQUYEN),
    KEY IX_QND_MAQUYEN (MAQUYEN),
    CONSTRAINT FK_QND_USER  FOREIGN KEY (user_id) REFERENCES users(id)   ON DELETE CASCADE,
    CONSTRAINT FK_QND_QUYEN FOREIGN KEY (MAQUYEN)  REFERENCES QUYEN(MAQUYEN)
) ENGINE=InnoDB;

-- =========================================================
-- KHÁCH HÀNG & ĐỊA CHỈ
-- =========================================================
CREATE TABLE KHACHHANG (
    MAKHACHHANG INT NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED,
    HOTEN VARCHAR(50) NOT NULL,
    SODIENTHOAI VARCHAR(10),
    EMAIL VARCHAR(255),
    PRIMARY KEY (MAKHACHHANG),
    KEY IX_KH_user_id (user_id),
    CONSTRAINT FK_KH_USER FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DIACHI_GIAOHANG (
    MADIACHI INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG INT NOT NULL,
    DIACHI VARCHAR(255),
    PRIMARY KEY (MADIACHI),
    KEY IX_DC_MAKH (MAKHACHHANG),
    CONSTRAINT FK_DC_KH FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- =========================================================
-- HÌNH THỨC THANH TOÁN
-- =========================================================
CREATE TABLE HINHTHUCTT (
    MATT VARCHAR(10) NOT NULL,
    LOAITT VARCHAR(255),
    PRIMARY KEY (MATT)
) ENGINE=InnoDB;

-- =========================================================
-- SẢN PHẨM
-- =========================================================
CREATE TABLE SANPHAM 
(
    MASANPHAM    VARCHAR(10) NOT NULL,
    TENSANPHAM   VARCHAR(255) NOT NULL,
    HINHANH      VARCHAR(255),
    GIANHAP      DECIMAL(18,0) DEFAULT 0,
    GIABAN       DECIMAL(18,0) DEFAULT 0,
    SOLUONGTON   INT NOT NULL DEFAULT 0,
    MOTA         VARCHAR(1000),
    MALOAI       VARCHAR(10),
    MAKHUYENMAI  VARCHAR(10),
    MANHACUNGCAP INT NULL,
    PRIMARY KEY (MASANPHAM),
    KEY IX_SP_MALOAI (MALOAI),
    KEY IX_SP_MAKM (MAKHUYENMAI),
    KEY IX_SP_MANCC (MANHACUNGCAP),
    CONSTRAINT FK_SP_LOAI   FOREIGN KEY (MALOAI)       REFERENCES LOAI(MALOAI)                 ON DELETE CASCADE,
    CONSTRAINT FK_SP_KM     FOREIGN KEY (MAKHUYENMAI)  REFERENCES KHUYENMAI(MAKHUYENMAI)       ON DELETE SET NULL,
    CONSTRAINT FK_SP_NCC    FOREIGN KEY (MANHACUNGCAP) REFERENCES NHACUNGCAP(MANHACUNGCAP)     ON DELETE SET NULL
) ENGINE=InnoDB;

-- =========================================================
-- Liên kết SP - KM (cho phép 1 SP có nhiều KM)
-- =========================================================
CREATE TABLE SANPHAM_KHUYENMAI 
(
    MASANPHAM   VARCHAR(10) NOT NULL,
    MAKHUYENMAI VARCHAR(10) NOT NULL,
    PRIMARY KEY (MASANPHAM, MAKHUYENMAI),
    KEY IX_SPKM_MASP (MASANPHAM),
    KEY IX_SPKM_MAKM (MAKHUYENMAI),
    CONSTRAINT FK_SPKM_SP FOREIGN KEY (MASANPHAM)   REFERENCES SANPHAM(MASANPHAM)     ON DELETE CASCADE,
    CONSTRAINT FK_SPKM_KM FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- Đánh giá
-- =========================================================
CREATE TABLE DANHGIA 
(
    MADANHGIA    INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG  INT NOT NULL,
    MASANPHAM    VARCHAR(10) NOT NULL,
    DIEMSO       INT CHECK (DIEMSO BETWEEN 1 AND 5),
    NHANXET      VARCHAR(1000),
    NGAYDANHGIA  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MADANHGIA),
    UNIQUE KEY UX_DANHGIA_KH_SP (MAKHACHHANG, MASANPHAM),
    KEY IX_DANHGIA_SP (MASANPHAM),
    KEY IX_DANHGIA_KH (MAKHACHHANG),
    CONSTRAINT FK_DG_KH  FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE CASCADE,
    CONSTRAINT FK_DG_SP  FOREIGN KEY (MASANPHAM)   REFERENCES SANPHAM(MASANPHAM)     ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- Liên hệ (hộp thư ý kiến)
-- =========================================================
CREATE TABLE LIENHE (
    ID           INT NOT NULL AUTO_INCREMENT,
    NAME         VARCHAR(120)  NOT NULL,
    EMAIL        VARCHAR(255)  NOT NULL,
    MESSAGE      VARCHAR(5000) NOT NULL,
    STATUS       ENUM('NEW','READ','REPLIED') NOT NULL DEFAULT 'NEW',
    REPLY_MESSAGE VARCHAR(5000) NULL,
    REPLY_BY     BIGINT UNSIGNED NULL,   -- users.id (nhân viên phản hồi)
    CREATED_AT   DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT   DATETIME NULL,
    REPLIED_AT   DATETIME NULL,
    PRIMARY KEY (ID),
    KEY IX_LH_STATUS (STATUS),
    KEY IX_LH_EMAIL  (EMAIL),
    CONSTRAINT FK_LH_REPLY_BY FOREIGN KEY (REPLY_BY) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- =========================================================
-- ĐƠN HÀNG & CHI TIẾT
-- =========================================================
CREATE TABLE DONHANG 
(
    MADONHANG      INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG    INT NOT NULL,
    MADIACHI       INT NOT NULL,
    NGAYGIAO       DATETIME NULL,
    NGAYDAT        DATETIME NULL,
    MATT           VARCHAR(10),
    GHICHU         VARCHAR(255),
    TONGSLHANG     INT DEFAULT 0,
    TONGTHANHTIEN  DECIMAL(18,0) DEFAULT 0,
    TRANGTHAI      VARCHAR(50) DEFAULT 'Chờ xử lý',
    PRIMARY KEY (MADONHANG),
    KEY IX_DH_MAKH (MAKHACHHANG),
    KEY IX_DH_MADC (MADIACHI),
    KEY IX_DH_MATT (MATT),
    CONSTRAINT FK_DH_KH   FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE CASCADE,
    CONSTRAINT FK_DH_DC   FOREIGN KEY (MADIACHI)    REFERENCES DIACHI_GIAOHANG(MADIACHI) ON DELETE RESTRICT,
    CONSTRAINT FK_DH_TT   FOREIGN KEY (MATT)        REFERENCES HINHTHUCTT(MATT)
) ENGINE=InnoDB;

ALTER TABLE DONHANG
    ADD COLUMN MAKHUYENMAI VARCHAR(10) NULL,
    ADD CONSTRAINT FK_DH_KM
        FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI)
        ON DELETE SET NULL;

CREATE TABLE CHITIETDONHANG 
(
    MADONHANG  INT NOT NULL,
    MASANPHAM  VARCHAR(10) NOT NULL,
    SOLUONG    INT NOT NULL DEFAULT 1,
    DONGIA     DECIMAL(18,0) NOT NULL DEFAULT 0,
    PRIMARY KEY (MADONHANG, MASANPHAM),
    KEY IX_CTDH_MASP (MASANPHAM),
    CONSTRAINT FK_CTDH_DH  FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG) ON DELETE CASCADE,
    CONSTRAINT FK_CTDH_SP  FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
) ENGINE=InnoDB;

-- =========================================================
-- PHIẾU NHẬP & CHI TIẾT (NHẬP HÀNG)
-- =========================================================
CREATE TABLE PHIEUNHAP (
    MAPN         INT NOT NULL AUTO_INCREMENT,
    MANHACUNGCAP INT NOT NULL,
    NGAYNHAP     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NHANVIEN_ID  BIGINT UNSIGNED NOT NULL,               -- users.id
    TRANGTHAI    ENUM('NHAP','DA_XAC_NHAN','HUY') NOT NULL DEFAULT 'NHAP',
    TONGSL       INT DEFAULT 0,
    GHICHU       VARCHAR(255),
    PRIMARY KEY (MAPN),
    KEY IX_PN_NCC (MANHACUNGCAP),
    KEY IX_PN_NV  (NHANVIEN_ID),
    CONSTRAINT FK_PN_NCC FOREIGN KEY (MANHACUNGCAP) REFERENCES NHACUNGCAP(MANHACUNGCAP) ON DELETE RESTRICT,
    CONSTRAINT FK_PN_NV  FOREIGN KEY (NHANVIEN_ID)  REFERENCES users(id)               ON DELETE RESTRICT
) ENGINE=InnoDB;

CREATE TABLE CT_PHIEUNHAP (
    MAPN        INT NOT NULL,
    MASANPHAM   VARCHAR(10) NOT NULL,
    SOLUONG     INT NOT NULL CHECK (SOLUONG > 0),
    DONGIA      DECIMAL(18,0) NOT NULL CHECK (DONGIA >= 0),  -- giá vốn theo dòng
    PRIMARY KEY (MAPN, MASANPHAM),
    KEY IX_CTPN_SP (MASANPHAM),
    CONSTRAINT FK_CTPN_PN FOREIGN KEY (MAPN)      REFERENCES PHIEUNHAP(MAPN)    ON DELETE CASCADE,
    CONSTRAINT FK_CTPN_SP FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- =========================================================
-- PHIẾU XUẤT & CHI TIẾT (XUẤT KHO/BÁN HÀNG)
-- =========================================================
CREATE TABLE PHIEUXUAT (
    MAPX         INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG  INT NULL,                   -- bán lẻ/tham chiếu KH
    MADIACHI     INT NOT NULL,
    NGAYXUAT     DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    NHANVIEN_ID  BIGINT UNSIGNED NOT NULL,
    TRANGTHAI    ENUM('NHAP','DA_XAC_NHAN','HUY') NOT NULL DEFAULT 'NHAP',
    TONGSL       INT DEFAULT 0,
    GHICHU       VARCHAR(255),
    MAKHUYENMAI VARCHAR(10) NULL,
    TONGTIEN DECIMAL(15,2) DEFAULT 0.00,
    PRIMARY KEY (MAPX),
    KEY IX_PX_KH (MAKHACHHANG),
    KEY IX_PX_NV (NHANVIEN_ID),
    CONSTRAINT FK_PX_DC FOREIGN KEY (MADIACHI) REFERENCES DIACHI_GIAOHANG(MADIACHI),
    CONSTRAINT FK_PX_KH FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG)   ON DELETE SET NULL,
    CONSTRAINT FK_PX_NV FOREIGN KEY (NHANVIEN_ID) REFERENCES users(id)                ON DELETE RESTRICT,
    CONSTRAINT FK_PX_KM FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI)
    ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE CT_PHIEUXUAT (
    MAPX        INT NOT NULL,
    MASANPHAM   VARCHAR(10) NOT NULL,
    SOLUONG     INT NOT NULL CHECK (SOLUONG > 0),
    DONGIA      DECIMAL(18,0) NOT NULL CHECK (DONGIA >= 0), -- đơn giá xuất/bán
    PRIMARY KEY (MAPX, MASANPHAM),
    KEY IX_CTPX_SP (MASANPHAM),
    CONSTRAINT FK_CTPX_PX FOREIGN KEY (MAPX)      REFERENCES PHIEUXUAT(MAPX)    ON DELETE CASCADE,
    CONSTRAINT FK_CTPX_SP FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- =========================================================
-- BẢNG HỆ THỐNG CHO LARAVEL
-- =========================================================

-- Cache store (Laravel database cache)
CREATE TABLE cache (
  `key` varchar(255) NOT NULL,
  `value` mediumtext NOT NULL,
  `expiration` int NOT NULL,
  PRIMARY KEY (`key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Sessions (nếu dùng SESSION_DRIVER=database)
CREATE TABLE sessions (
  `id` varchar(255) NOT NULL,
  `user_id` bigint unsigned NULL,
  `ip_address` varchar(45) NULL,
  `user_agent` text NULL,
  `payload` longtext NOT NULL,
  `last_activity` int NOT NULL,
  PRIMARY KEY (`id`),
  KEY `sessions_user_id_index` (`user_id`),
  KEY `sessions_last_activity_index` (`last_activity`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Queue: jobs (nếu QUEUE_CONNECTION=database)
CREATE TABLE jobs (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `queue` varchar(255) NOT NULL,
  `payload` longtext NOT NULL,
  `attempts` tinyint unsigned NOT NULL,
  `reserved_at` int unsigned DEFAULT NULL,
  `available_at` int unsigned NOT NULL,
  `created_at` int unsigned NOT NULL,
  PRIMARY KEY (`id`),
  KEY `jobs_queue_index` (`queue`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Queue: failed_jobs (ghi nhận job lỗi)
CREATE TABLE failed_jobs (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `uuid` varchar(255) DEFAULT NULL,
  `connection` text NOT NULL,
  `queue` text NOT NULL,
  `payload` longtext NOT NULL,
  `exception` longtext NOT NULL,
  `failed_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Queue: job_batches (nếu bạn dùng Bus batching)
CREATE TABLE job_batches (
  `id` varchar(255) NOT NULL,
  `name` varchar(255) DEFAULT NULL,
  `total_jobs` int NOT NULL,
  `pending_jobs` int NOT NULL,
  `failed_jobs` int NOT NULL,
  `failed_job_ids` longtext,
  `options` mediumtext,
  `cancelled_at` int DEFAULT NULL,
  `created_at` int NOT NULL,
  `finished_at` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- =========================================================
-- TRIGGERS
-- =========================================================
DELIMITER $$

-- Tổng số lượng phiếu nhập
CREATE TRIGGER trg_ctpn_sync AFTER INSERT ON CT_PHIEUNHAP
FOR EACH ROW BEGIN
    UPDATE PHIEUNHAP SET TONGSL=(SELECT SUM(SOLUONG) FROM CT_PHIEUNHAP WHERE MAPN=NEW.MAPN) WHERE MAPN=NEW.MAPN;
END$$
CREATE TRIGGER trg_ctpn_sync_upd AFTER UPDATE ON CT_PHIEUNHAP
FOR EACH ROW BEGIN
    UPDATE PHIEUNHAP SET TONGSL=(SELECT SUM(SOLUONG) FROM CT_PHIEUNHAP WHERE MAPN=NEW.MAPN) WHERE MAPN=NEW.MAPN;
END$$
CREATE TRIGGER trg_ctpn_sync_del AFTER DELETE ON CT_PHIEUNHAP
FOR EACH ROW BEGIN
    UPDATE PHIEUNHAP SET TONGSL=(SELECT SUM(SOLUONG) FROM CT_PHIEUNHAP WHERE MAPN=OLD.MAPN) WHERE MAPN=OLD.MAPN;
END$$

-- Tổng số lượng phiếu xuất
CREATE TRIGGER trg_ctpx_sync AFTER INSERT ON CT_PHIEUXUAT
FOR EACH ROW BEGIN
    UPDATE PHIEUXUAT SET TONGSL=(SELECT SUM(SOLUONG) FROM CT_PHIEUXUAT WHERE MAPX=NEW.MAPX) WHERE MAPX=NEW.MAPX;
END$$
CREATE TRIGGER trg_ctpx_sync_upd AFTER UPDATE ON CT_PHIEUXUAT
FOR EACH ROW BEGIN
    UPDATE PHIEUXUAT SET TONGSL=(SELECT SUM(SOLUONG) FROM CT_PHIEUXUAT WHERE MAPX=NEW.MAPX) WHERE MAPX=NEW.MAPX;
END$$
CREATE TRIGGER trg_ctpx_sync_del AFTER DELETE ON CT_PHIEUXUAT
FOR EACH ROW BEGIN
    UPDATE PHIEUXUAT SET TONGSL=(SELECT SUM(SOLUONG) FROM CT_PHIEUXUAT WHERE MAPX=OLD.MAPX) WHERE MAPX=OLD.MAPX;
END$$

-- Xác nhận/hủy phiếu nhập: cộng/trừ tồn kho
CREATE TRIGGER trg_pn_after_update AFTER UPDATE ON PHIEUNHAP
FOR EACH ROW BEGIN
    IF OLD.TRANGTHAI <> 'DA_XAC_NHAN' AND NEW.TRANGTHAI='DA_XAC_NHAN' THEN
        UPDATE SANPHAM s JOIN CT_PHIEUNHAP d ON s.MASANPHAM=d.MASANPHAM
        SET s.SOLUONGTON=s.SOLUONGTON+d.SOLUONG WHERE d.MAPN=NEW.MAPN;
    END IF;
    IF OLD.TRANGTHAI='DA_XAC_NHAN' AND NEW.TRANGTHAI='HUY' THEN
        UPDATE SANPHAM s JOIN CT_PHIEUNHAP d ON s.MASANPHAM=d.MASANPHAM
        SET s.SOLUONGTON=s.SOLUONGTON-d.SOLUONG WHERE d.MAPN=NEW.MAPN;
    END IF;
END$$

-- Kiểm tra tồn và xác nhận/hủy phiếu xuất: trừ/cộng tồn kho
CREATE TRIGGER trg_px_before_confirm BEFORE UPDATE ON PHIEUXUAT
FOR EACH ROW BEGIN
    IF OLD.TRANGTHAI <> 'DA_XAC_NHAN' AND NEW.TRANGTHAI='DA_XAC_NHAN' THEN
        IF EXISTS(SELECT 1 FROM CT_PHIEUXUAT d JOIN SANPHAM s ON d.MASANPHAM=s.MASANPHAM
                WHERE d.MAPX=NEW.MAPX AND s.SOLUONGTON<d.SOLUONG) THEN
            SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Khong du ton kho de xuat';
        END IF;
    END IF;
END$$
CREATE TRIGGER trg_px_after_update AFTER UPDATE ON PHIEUXUAT
FOR EACH ROW BEGIN
    IF OLD.TRANGTHAI <> 'DA_XAC_NHAN' AND NEW.TRANGTHAI='DA_XAC_NHAN' THEN
        UPDATE SANPHAM s JOIN CT_PHIEUXUAT d ON s.MASANPHAM=d.MASANPHAM
        SET s.SOLUONGTON=s.SOLUONGTON-d.SOLUONG WHERE d.MAPX=NEW.MAPX;
    END IF;
    IF OLD.TRANGTHAI='DA_XAC_NHAN' AND NEW.TRANGTHAI='HUY' THEN
        UPDATE SANPHAM s JOIN CT_PHIEUXUAT d ON s.MASANPHAM=d.MASANPHAM
        SET s.SOLUONGTON=s.SOLUONGTON+d.SOLUONG WHERE d.MAPX=NEW.MAPX;
    END IF;
END$$

DELIMITER ;