-- =========================================================
-- QL_MYNGHE - HỆ THỐNG QUẢN LÝ CỬA HÀNG MỸ NGHỆ (Laravel UI)
-- =========================================================
DROP DATABASE IF EXISTS QL_MYNGHE;
CREATE DATABASE QL_MYNGHE
    DEFAULT CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;
USE QL_MYNGHE;

-- =========================================================
-- DANHMUCSANPHAM
-- =========================================================
CREATE TABLE DANHMUCSANPHAM 
(
    MADANHMUC INT NOT NULL AUTO_INCREMENT,
    TENDANHMUC VARCHAR(100) NOT NULL,
    PRIMARY KEY (MADANHMUC)
) ENGINE=InnoDB;

-- =========================================================
-- LOAI
-- =========================================================
CREATE TABLE LOAI 
(
    MALOAI VARCHAR(10) NOT NULL,
    TENLOAI VARCHAR(50) NOT NULL,
    MADANHMUC INT,
    PRIMARY KEY (MALOAI),
    KEY IX_LOAI_MADANHMUC (MADANHMUC),
    CONSTRAINT FK_LOAI_DANHMUC
        FOREIGN KEY (MADANHMUC) REFERENCES DANHMUCSANPHAM(MADANHMUC)
        ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- KHUYENMAI
-- =========================================================
CREATE TABLE KHUYENMAI 
(
    MAKHUYENMAI VARCHAR(10) NOT NULL,
    LOAIKHUYENMAI VARCHAR(50),
    TENKHUYENMAI VARCHAR(100),
    NGAYBATDAU DATETIME,
    NGAYKETTHUC DATETIME,
    GIAMGIA DECIMAL(5,2),
    PRIMARY KEY (MAKHUYENMAI)
) ENGINE=InnoDB;

-- =========================================================
-- NHACUNGCAP
-- =========================================================
CREATE TABLE NHACUNGCAP 
(
    MANHACUNGCAP INT NOT NULL AUTO_INCREMENT,
    TENNHACUNGCAP VARCHAR(100) NOT NULL,
    DTHOAI VARCHAR(20),
    DIACHI VARCHAR(255),
    PRIMARY KEY (MANHACUNGCAP)
) ENGINE=InnoDB;

-- =========================================================
-- USERS / QUYEN
-- =========================================================
CREATE TABLE users 
(
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    phone VARCHAR(20),
    remember_token VARCHAR(100),
    created_at TIMESTAMP NULL DEFAULT NULL,
    updated_at TIMESTAMP NULL DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE QUYEN 
(
    MAQUYEN VARCHAR(10) NOT NULL,
    TENQUYEN VARCHAR(50) NOT NULL,
    PRIMARY KEY (MAQUYEN)
) ENGINE=InnoDB;

CREATE TABLE QUYEN_NGUOIDUNG 
(
    user_id BIGINT UNSIGNED NOT NULL,
    MAQUYEN VARCHAR(10) NOT NULL,
    PRIMARY KEY (user_id, MAQUYEN),
    KEY IX_QND_MAQUYEN (MAQUYEN),
    CONSTRAINT FK_QND_USER  FOREIGN KEY (user_id) REFERENCES users(id)   ON DELETE CASCADE,
    CONSTRAINT FK_QND_QUYEN FOREIGN KEY (MAQUYEN)  REFERENCES QUYEN(MAQUYEN)
) ENGINE=InnoDB;

-- =========================================================
-- KHÁCH HÀNG & ĐỊA CHỈ
-- =========================================================
CREATE TABLE KHACHHANG (
    MAKHACHHANG INT NOT NULL AUTO_INCREMENT,
    user_id BIGINT UNSIGNED,
    HOTEN VARCHAR(50) NOT NULL,
    SODIENTHOAI VARCHAR(10),
    EMAIL VARCHAR(255),
    PRIMARY KEY (MAKHACHHANG),
    KEY IX_KH_user_id (user_id),
    CONSTRAINT FK_KH_USER FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

CREATE TABLE DIACHI_GIAOHANG (
    MADIACHI INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG INT NOT NULL,
    DIACHI VARCHAR(255),
    PRIMARY KEY (MADIACHI),
    KEY IX_DC_MAKH (MAKHACHHANG),
    CONSTRAINT FK_DC_KH FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE RESTRICT
) ENGINE=InnoDB;

-- =========================================================
-- HÌNH THỨC THANH TOÁN
-- =========================================================
CREATE TABLE HINHTHUCTT (
    MATT VARCHAR(10) NOT NULL,
    LOAITT VARCHAR(255),
    PRIMARY KEY (MATT)
) ENGINE=InnoDB;

-- =========================================================
-- SẢN PHẨM
-- =========================================================
CREATE TABLE SANPHAM 
(
    MASANPHAM VARCHAR(10) NOT NULL,
    TENSANPHAM VARCHAR(255) NOT NULL,
    HINHANH VARCHAR(255),
    GIABAN DECIMAL(18,0),
    SOLUONGTON INT,
    MOTA VARCHAR(1000),
    MALOAI VARCHAR(10),
    MAKHUYENMAI VARCHAR(10),
    MANHACUNGCAP INT,
    PRIMARY KEY (MASANPHAM),
    KEY IX_SP_MALOAI (MALOAI),
    KEY IX_SP_MAKM (MAKHUYENMAI),
    KEY IX_SP_MANCC (MANHACUNGCAP),
    CONSTRAINT FK_SP_LOAI   FOREIGN KEY (MALOAI)       REFERENCES LOAI(MALOAI)                 ON DELETE CASCADE,
    CONSTRAINT FK_SP_KM     FOREIGN KEY (MAKHUYENMAI)  REFERENCES KHUYENMAI(MAKHUYENMAI)       ON DELETE SET NULL,
    CONSTRAINT FK_SP_NCC    FOREIGN KEY (MANHACUNGCAP) REFERENCES NHACUNGCAP(MANHACUNGCAP)     ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- Liên kết SP - KM (nếu 1 SP có nhiều KM)
-- =========================================================
CREATE TABLE SANPHAM_KHUYENMAI 
(
    MASANPHAM   VARCHAR(10) NOT NULL,
    MAKHUYENMAI VARCHAR(10) NOT NULL,
    PRIMARY KEY (MASANPHAM, MAKHUYENMAI),
    KEY IX_SPKM_MASP (MASANPHAM),
    KEY IX_SPKM_MAKM (MAKHUYENMAI),
    CONSTRAINT FK_SPKM_SP FOREIGN KEY (MASANPHAM)   REFERENCES SANPHAM(MASANPHAM)     ON DELETE CASCADE,
    CONSTRAINT FK_SPKM_KM FOREIGN KEY (MAKHUYENMAI) REFERENCES KHUYENMAI(MAKHUYENMAI) ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- Đánh giá
-- =========================================================
CREATE TABLE DANHGIA 
(
    MADANHGIA    INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG  INT NOT NULL,
    MASANPHAM    VARCHAR(10) NOT NULL,
    DIEMSO       INT CHECK (DIEMSO BETWEEN 1 AND 5),
    NHANXET      VARCHAR(1000),
    NGAYDANHGIA  DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (MADANHGIA),
    -- Ràng buộc 1 khách hàng chỉ 1 đánh giá / 1 sản phẩm
    UNIQUE KEY UX_DANHGIA_KH_SP (MAKHACHHANG, MASANPHAM),
    -- Index để load nhanh theo sản phẩm
    KEY IX_DANHGIA_SP (MASANPHAM),
    KEY IX_DANHGIA_KH (MAKHACHHANG),
    CONSTRAINT FK_DG_KH  FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE CASCADE,
    CONSTRAINT FK_DG_SP  FOREIGN KEY (MASANPHAM)   REFERENCES SANPHAM(MASANPHAM)     ON DELETE CASCADE
) ENGINE=InnoDB;

-- =========================================================
-- ĐƠN HÀNG
-- =========================================================
CREATE TABLE DONHANG 
(
    MADONHANG      INT NOT NULL AUTO_INCREMENT,
    MAKHACHHANG    INT NOT NULL,
    MADIACHI       INT NOT NULL,
    NGAYGIAO       DATETIME NULL,
    NGAYDAT        DATETIME NULL,
    MATT           VARCHAR(10),
    GHICHU         VARCHAR(255),
    TONGSLHANG     INT,
    TONGTHANHTIEN  DECIMAL(18,0),
    TRANGTHAI      VARCHAR(50) DEFAULT 'Chờ xử lý',
    PRIMARY KEY (MADONHANG),
    KEY IX_DH_MAKH (MAKHACHHANG),
    KEY IX_DH_MADC (MADIACHI),
    KEY IX_DH_MATT (MATT),
    CONSTRAINT FK_DH_KH   FOREIGN KEY (MAKHACHHANG) REFERENCES KHACHHANG(MAKHACHHANG) ON DELETE CASCADE,
    CONSTRAINT FK_DH_DC   FOREIGN KEY (MADIACHI)    REFERENCES DIACHI_GIAOHANG(MADIACHI) ON DELETE RESTRICT,
    CONSTRAINT FK_DH_TT   FOREIGN KEY (MATT)        REFERENCES HINHTHUCTT(MATT)
) ENGINE=InnoDB;

CREATE TABLE CHITIETDONHANG 
(
    MADONHANG  INT NOT NULL,
    MASANPHAM  VARCHAR(10) NOT NULL,
    SOLUONG    INT,
    DONGIA     DECIMAL(18,0),
    PRIMARY KEY (MADONHANG, MASANPHAM),
    KEY IX_CTDH_MASP (MASANPHAM),
    CONSTRAINT FK_CTDH_DH  FOREIGN KEY (MADONHANG) REFERENCES DONHANG(MADONHANG) ON DELETE CASCADE,
    CONSTRAINT FK_CTDH_SP  FOREIGN KEY (MASANPHAM) REFERENCES SANPHAM(MASANPHAM)
) ENGINE=InnoDB;
